version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3000"              # Puedes cambiar el puerto externo si 3000 ya lo usa el frontend
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  frontend:
    image: node:16
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend/app:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"
    depends_on:
      - backend                  # Espera que el backend est√© arriba

  db:
    image: mongo:6-jammy
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: abp
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: